/** Build the Claude-Code-optimized markdown changelog from a document. */

import type { RedlineDocument } from '../model/document';
import type {
  ChangeRequestAnnotation,
  ElementMetadata,
  TextEditShape,
} from '../model/annotation';

/** Render the document as a change-request markdown file. */
export function buildMarkdown(
  doc: RedlineDocument,
  screenshotFilename: string,
): string {
  const changes = doc.annotations.filter(
    (a): a is ChangeRequestAnnotation => a.annotationClass === 'change-request',
  );
  const emphasisCount = doc.annotations.length - changes.length;
  const out: string[] = [];

  out.push('# Redline Change Request');
  out.push('');
  out.push(
    '> Generated by the Redline browser extension. Each numbered item below is',
  );
  out.push(
    '> a requested change to the page. The attached screenshot shows the same',
  );
  out.push('> numbers as visual markers.');
  out.push('');
  out.push('| Field | Value |');
  out.push('| --- | --- |');
  out.push(`| Page | ${cell(doc.pageTitle)} |`);
  out.push(`| URL | ${cell(doc.pageUrl)} |`);
  out.push(`| Captured | ${formatDate(doc.updatedAt)} |`);
  out.push(
    `| Viewport | ${doc.viewport.width}x${doc.viewport.height} @ ${doc.viewport.devicePixelRatio}x |`,
  );
  out.push(`| Screenshot | ${cell(screenshotFilename)} |`);
  out.push(`| Changes | ${changes.length} |`);
  out.push('');
  out.push('## How to apply');
  out.push('');
  out.push('1. Open the screenshot to see each numbered marker in context.');
  out.push(
    '2. For each change, find the element in your source code. Modern sites',
  );
  out.push(
    '   hash their class names (Tailwind, CSS modules, styled-components), so',
  );
  out.push(
    '   the Selector may not appear verbatim in the source. Fall back to the',
  );
  out.push(
    '   Element context, current text, id, and data attributes to locate it.',
  );
  out.push(
    '3. For a text replacement (Change type: text replacement), search the',
  );
  out.push(
    '   source for the exact Old text string and replace it with the New',
  );
  out.push(
    '   text. That is more reliable than the selector. Fall back to the',
  );
  out.push(
    '   selector only if the Old text is not found verbatim, for instance',
  );
  out.push(
    '   when it is interpolated, split across lines, or a translation key.',
  );
  out.push('4. Make the change. Keep it minimal and scoped to the request.');
  out.push('5. Report per item: Done / Skipped (reason) / Needs clarification.');
  out.push('');
  out.push('## Changes');
  out.push('');

  if (changes.length === 0) {
    out.push('_No labeled changes were captured._');
    out.push('');
  }
  for (const change of changes) {
    if (change.geometry.kind === 'textedit') {
      appendTextEdit(out, change.geometry, change.number);
      appendElement(out, change.element);
      out.push('');
      continue;
    }
    const label = change.label.trim() || '(no label)';
    out.push(`### ${change.number}. ${label}`);
    out.push('');
    out.push(`- Requested change: ${change.label.trim() || '(none given)'}`);
    appendElement(out, change.element);
    out.push('');
  }

  if (emphasisCount > 0) {
    out.push('## Visual emphasis (no code change)');
    out.push('');
    out.push(
      `${emphasisCount} non-numbered mark(s) in the screenshot indicate areas`,
    );
    out.push('of attention only. No direct change is requested for them.');
    out.push('');
  }

  out.push('---');
  out.push(`*${changes.length} change(s) · Redline · schema v1*`);
  out.push('');
  return out.join('\n');
}

function appendElement(out: string[], el: ElementMetadata | null): void {
  if (!el) {
    out.push('- Element: (no element under the marker, see the screenshot)');
    return;
  }
  out.push(`- Selector: \`${el.selector}\``);
  out.push(`- Selector path: \`${el.selectorPath}\``);
  out.push(`- XPath: \`${el.xpath}\``);
  if (el.inShadowDom) {
    out.push(
      '- Shadow DOM: this element is inside a shadow root. The Selector, ' +
        'Selector path, and XPath above point at the shadow host component; ' +
        'find the element inside that component by its tag and text.',
    );
  }
  out.push(`- Element: ${describeElement(el)}`);
  if (el.textSnippet) out.push(`- Current text: "${el.textSnippet}"`);
  const data = Object.entries(el.dataAttributes);
  if (data.length > 0) {
    out.push(
      `- Data attributes: ${data.map(([k, v]) => `${k}="${v}"`).join(', ')}`,
    );
  }
  const vp = el.viewportPercent;
  out.push(`- Location: ${vp.top}% from top, ${vp.left}% from left of viewport`);
  if (el.nearbyLandmark) out.push(`- Nearby landmark: ${el.nearbyLandmark}`);
}

/** Append a text-replacement change: the verbatim before and after text. */
function appendTextEdit(
  out: string[],
  geometry: TextEditShape,
  number: number,
): void {
  out.push(`### ${number}. Text edit`);
  out.push('');
  out.push('- Change type: text replacement');
  out.push(`- Old text: "${geometry.oldText}"`);
  out.push(`- New text: "${geometry.newText}"`);
  if (geometry.hasInlineMarkup) {
    out.push(
      '- Contains inline markup: yes. The element holds child elements ' +
        '(a link, bold text, an icon). Replace the text and keep that ' +
        'markup intact.',
    );
  }
}

function describeElement(el: ElementMetadata): string {
  const attrs: string[] = [];
  if (el.id) attrs.push(`id="${el.id}"`);
  if (el.classList.length > 0) {
    attrs.push(`class="${el.classList.join(' ')}"`);
  }
  const openTag = `<${el.tag}${attrs.length > 0 ? ' ' + attrs.join(' ') : ''}>`;
  const notes: string[] = [];
  if (el.role) notes.push(`role: ${el.role}`);
  if (el.ariaLabel) notes.push(`aria-label: "${el.ariaLabel}"`);
  return notes.length > 0
    ? `\`${openTag}\` (${notes.join(', ')})`
    : `\`${openTag}\``;
}

/** Escape a value for use inside a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Format an ISO timestamp as `YYYY-MM-DD HH:MM`. */
function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(
    d.getDate(),
  )} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
